### PR TITLE
Adding example TypeSpec definition for CLU

### PR DESCRIPTION
**Pull request by Zach-King2**

### CODE REVIEW

**Comment by Zach-King2** [comment]
@heaths

**Review by heaths — CHANGES_REQUESTED** [review]
Could you make the PR title something descriptive, like "Adding example TypeSpec definition for CLU" or something like that? It helps to track down changes later.

**Comment by Zach-King2** [comment]
> Could you make the PR title something descriptive, like "Adding example TypeSpec definition for CLU" or something like that? It helps to track down changes later.

**Comment by heaths** [comment]
While you're at it, could you also add me to the root [_CODEOWNERS_ file](https://github.com/Azure/azure-rest-api-specs/blob/5a9afce8360020c46b38841e04179447a28118b2/CODEOWNERS#L71)? Something like:

```codeowners
/specification/cognitiveservices/Language.Conversations/ @kristapratico @heaths
```

**Comment by Zach-King2** [comment]
> While you're at it, could you also add me to the root [_CODEOWNERS_ file](https://github.com/Azure/azure-rest-api-specs/blob/5a9afce8360020c46b38841e04179447a28118b2/CODEOWNERS#L71)? Something like:
> 
> ```
> /specification/cognitiveservices/Language.Conversations/ @kristapratico @heaths
> ```

I just added this line.

**Review by heaths — APPROVED** [review]

**Pull request closed without merging**
